# Generated by Django 4.1.6 on 2023-02-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maxsus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=50)),
            ],
        ),
    ]
